services:

  # SQL Server
  pagueveloz-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: pagueveloz-sql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Aa123456!"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - pagueveloz-net

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: pagueveloz-rabbitmq
    ports:
      - "5672:5672"    # porta AMQP
      - "15672:15672"  # dashboard web
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - pagueveloz-net

  # API
  pagueveloz-api:
    image: reinaldofc80/pagueveloz-api:latest
    container_name: pagueveloz-api
    depends_on:
      - pagueveloz-db
      - rabbitmq
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=pagueveloz-db;Database=PagueVeloz;User=sa;Password=Aa123456!;TrustServerCertificate=True"
      RabbitMQ__HostName: "rabbitmq"
      RabbitMQ__UserName: "guest"
      RabbitMQ__Password: "guest"
    ports:
      - "8080:8080"  # API + Swagger
      - "9090:9090"  # Prometheus metrics
    networks:
      - pagueveloz-net
    command: >
      sh -c "dotnet ef database update --no-build &&
             dotnet PagueVeloz.Api.dll"

networks:
  pagueveloz-net:

volumes:
  sqlserver_data:
