version: "3.9"

services:
  pagueveloz-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: pagueveloz-sql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Aa123456!"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - pagueveloz-net
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Aa123456! -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 20
      timeout: 10s

  pagueveloz-api:
    build:
      context: .
      dockerfile: PagueVeloz.Api/Dockerfile
    container_name: pagueveloz-api
    depends_on:
      pagueveloz-db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=pagueveloz-db;Database=PagueVeloz;User=sa;Password=Aa123456!;TrustServerCertificate=True"
    ports:
      - "8080:8080"
    networks:
      - pagueveloz-net
    command: >
      sh -c "dotnet ef database update --no-build &&
             dotnet PagueVeloz.Api.dll"

networks:
  pagueveloz-net:

volumes:
  sqlserver_data:
